### PR TITLE
Fix Object.assign error in IE11

### LINKED ISSUE #145: Issues in Interner Explorer
This line is not working in Interner Explorer
https://github.com/simplabs/ember-cookies/blob/7a7c68d36617ad23978bb6af9481e75f0d3e08a8/addon/services/cookies.js#L9

and babel don't transform this line
https://babeljs.io/docs/plugins/transform-object-assign/#caveats

### PR DESCRIPTION
**Pull request by XaserAcheron**
Closes #145 

This just does the classic Ember.assign fallback if Object.assign isn't defined (i.e. in IE ;)

### CODE REVIEW

File: addon/services/cookies.js [hunk 1]
```diff
@@ -5,8 +5,9 @@ import { assert } from '@ember/debug';
 import { A } from '@ember/array';
 import { getOwner } from '@ember/application';
 import Service from '@ember/service';
-import { merge } from '@ember/polyfills';
-const { keys, assign } = Object;
+import { merge, assign as emberAssign } from '@ember/polyfills';
+const { keys } = Object;
+const assign = Object.assign || emberAssign || merge;
```
Comment (marcoow) [inline addon/services/cookies.js]: I guess `emberAssign` would always be present so the fallback to `|| merge` is not necessary? We could even just always use `emberAssign`.

**Comment by marcoow** [comment]
I rebased on `master` which should fix the breaking build.

File: addon/services/cookies.js (hunk 1 above)
Comment (XaserAcheron) [reply addon/services/cookies.js]: Ember.assign was added in Ember 2.5, so the merge fallback is there for older version support. It's a fairly common pattern, I've seen.

Comment (marcoow) [reply addon/services/cookies.js]: Yes, you're right of course 🤦‍♂️

Comment (XaserAcheron) [reply addon/services/cookies.js]: Heh, no worries -- I do that all the time.

Thanks for the merge! :)
